### ISSUE TITLE
Question regarding HeatMapLayer

### ISSUE THREAD

**Issue by wassimz** [mstahv/g-leaflet-heat#1]
Hi,

Just aquick question regarding the create function (maybe I am wrong). In you provided parameter, you provide JsArray(LatLng), but in case you use Point3D with altitude, you this is passed to the Javascript  create function ??

Thanks

**Comment by mstahv** [comment]
Point3D is currently only available on the server side v-leaflet project. It generates raw JSON with the altitude attribute as well. Although the type parameter is plain LatLng (which is a "JS overlay type") in the create method, it can also carry JS objects with the altitude value and that is the only thing the underlaying JS library cares. The underlaying JS library knows nothing about GWT code.

I hope I managed to tackle the answer :-) If not, feel free to re-open the issue.
